name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run Go tests
        run: go test ./...
